version: '3'

networks:
  app-network:
    driver: bridge

services:
  postgres:
      image: postgres:15
      container_name: postgres-db
      environment:
        POSTGRES_DB: monitoring
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pass
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - app-network          
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: jar-prod
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vue-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    restart: unless-stopped
    networks:
      - app-network
  
volumes:
  postgres_data: {}      