version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: jar-prod
    ports:
      - "8080:8080"
    #mem_limit: 512m
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network
  # Nginx (отдача Laravel API + статики Vue)
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: nginx-prod
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend
  
  
volumes:
  postgres_data: {}