version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # PHP-FPM (Laravel)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: laravel-app-prod
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=production
      - DB_HOST=db
    restart: unless-stopped
    networks:
      - app-network

  # Nginx (отдача Laravel API + статики Vue)
  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # MySQL
  db:
    image: mysql:8.0
    container_name: db-prod
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network

volumes:
  dbdata: