version: '3'
services:
  laravel-setup:
    build:
      context: .
      dockerfile: Dockerfile.setup
    container_name: laravel-setup
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true