FROM php:8.2-cli

# Установка зависимостей
RUN apt-get update && apt-get install -y git unzip zip libzip-dev zlib1g-dev \
    libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libxml2-dev default-libmysqlclient-dev

# Установка расширений PHP
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install -j$(nproc) zip exif mbstring pdo_mysql gd pcntl bcmath sockets xml

# Установка Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app